### ISSUE TITLE
Problem with gryphon-cdecimal package 

### ISSUE THREAD

**Issue by pjmichalski** [AnonGit90210/RamanujanMachine#10]
Hi,
I recently successfully installed your software on a Windows 10 machine, but I wanted to make you aware of an issue I encountered. The requirements file lists the gryphon-cdecimal package, which I could not install because there was some issue with the C++ and my machine could not build the wheel file (my c++ compilers are up-to-date and work fine). I'm not sure what's the difference between gryphon-cdecimal and the regular cdecimal package, but in all recent versions of Python cdecimal is included as the replacement for the decimal package. When I realized this, I just skipped installing gryphon-cdecimal, and so far everything runs fine on my machine. So maybe you can remove gryphon-cdecimal from the requirements file? Or at least let people know they don't need it if they're using a recent version of Python? 

By the way, I love the project!

**Comment by AnonGit90210** [comment]
Hi,
This is actually a legacy requirement we forgot to remove, since we switched to use mpmath instead. Fixed it now.
Thanks!
