### ISSUE TITLE
Error when hashtable_file_operation=use

### ISSUE THREAD

**Issue by pjmichalski** [AnonGit90210/RamanujanMachine#11]
When hashtable_file_operation=use, the program seems to always set const=e, regardless of what's defined in the ini file. The main program does report that it read in the correct constant (i.e., pi), but the calculations are performed with const=e. It should be easy to reproduce this bug, but I can provide the ini and pkl files if needed.

**Comment by AnonGit90210** [comment]
Hello,
The target constant is being saved during generation or expansion of a hashtable. There's a logic behind it, as partial click results are being saved to the same hashtable during the run, to be able to manually restore the run in case of an accidental stop. Therefore, if one wishes to use a new constant with an existing hashtable, one should run once with "expand" and the desired new target constant (the a,b parameters can both be over a null interval, such as [[[1, 1]]]). This will set the new constant in the hashtable file. Then one can run it regularly with 'use' to seek new identities.
We'll consider applying a better policy (such as updating it automatically). In the meanwhile, a note about it was added to the readme file.
Thanks for pointing this out.
