### ISSUE TITLE
Port on top of Coq and UniMath

### ISSUE THREAD

**Issue by XVilka** [AnonGit90210/RamanujanMachine#2]
Would be interesting to operate conjectures in terms of [Coq](https://github.com/coq/coq) and [UniMath](https://github.com/UniMath/UniMath).

See also its [usage guide](https://github.com/UniMath/UniMath/blob/master/USAGE.md).

For example, there is a project aiming to try ML for theorem proving: https://github.com/ml4tp/gamepad

> GamePad is a Python library that exposes parts of the Coq ITP to enable machine learning.
Representing Coq Proofs

> We expose the proof trace obtained from Coq as Python data structures, including Coq’s mid-level and kernel-level term languages, proof states, proof steps, and proof trees so that they can be manipulated with arbitrary Python code.

**Comment by AnonGit90210** [comment]
Thank you for the suggestion!
The vision is a complete system that will cover the whole process, from conjecture to proof.
We noticed a gap in the conjecturing stage (and recently became aware of relevant work in the topic, to which we refer in an updated paper, soon to be released). In future, integrating with these or similar projects will certainly be the next step to take.
